# Generated by Django 3.0 on 2021-03-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=50, verbose_name='title')),
                ('price', models.IntegerField(db_column='price', verbose_name='price')),
                ('link', models.CharField(db_column='link', max_length=200, verbose_name='link')),
                ('city', models.CharField(db_column='city', max_length=20, verbose_name='city')),
            ],
            options={
                'db_table': 'advertisement',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('flag', models.CharField(db_column='flag', db_index=True, max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='flag')),
                ('name', models.CharField(db_column='name', max_length=20, unique=True, verbose_name='name')),
                ('city', models.CharField(db_column='city', max_length=20, verbose_name='city')),
                ('pinyin', models.CharField(db_column='pinyin', max_length=40, verbose_name='pinyin')),
            ],
            options={
                'db_table': 'airport',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date', verbose_name='date')),
                ('start_time', models.TimeField(db_column='start_time', verbose_name='start_time')),
                ('end_time', models.TimeField(db_column='end_time', verbose_name='end_time')),
                ('airline', models.CharField(db_column='airline', max_length=20, verbose_name='airline')),
                ('catagory', models.CharField(db_column='catagory', max_length=10, verbose_name='catagory')),
                ('price', models.IntegerField(db_column='price', verbose_name='price')),
                ('discount', models.DecimalField(db_column='discount', decimal_places=2, max_digits=3, verbose_name='discount')),
                ('end_airport', models.ForeignKey(db_column='end_airport', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_tickets', to='ticket.Airport', verbose_name='end_airport')),
                ('start_airport', models.ForeignKey(db_column='start_airport', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_tickets', to='ticket.Airport', verbose_name='start_airport')),
            ],
            options={
                'verbose_name': 'tickets',
                'db_table': 'ticket',
                'ordering': ['date', 'start_time', 'price'],
                'get_latest_by': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=20, verbose_name='name')),
                ('password', models.CharField(db_column='password', max_length=20, verbose_name='password')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=40, null=True, verbose_name='email')),
                ('tel', models.CharField(db_column='tel', max_length=12, verbose_name='tel')),
                ('gender', models.BooleanField(choices=[(True, 'male'), (False, 'female')], db_column='gender', verbose_name='gender')),
                ('addr', models.CharField(db_column='address', max_length=100, verbose_name='address')),
                ('tickets', models.ManyToManyField(db_table='user_ticket', related_name='users', to='ticket.Ticket', verbose_name='tickets')),
            ],
            options={
                'verbose_name': 'users',
                'db_table': 'user',
            },
        ),
    ]
