# Generated by Django 3.0 on 2021-03-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20210313_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': '广告表', 'verbose_name_plural': '广告表'},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': '机票表', 'verbose_name_plural': '机场表'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'get_latest_by': ['date', 'start_time'], 'ordering': ['date', 'start_time', 'price'], 'verbose_name': '机票表', 'verbose_name_plural': '机票表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
