# Generated by Django 3.0 on 2021-03-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20210315_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tickets',
        ),
        migrations.AddField(
            model_name='user',
            name='user_tickets',
            field=models.ManyToManyField(db_table='user_tickets', related_name='users', to='ticket.Ticket', verbose_name='tickets'),
        ),
    ]
