# Generated by Django 3.0 on 2021-03-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20210315_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='AoyouTicket',
        ),
    ]
