# Generated by Django 3.0 on 2021-04-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20210315_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(db_column='money', default=10000, verbose_name='money'),
        ),
    ]
